### ISSUE TITLE
sna::gtrans() does not work with network objects from intergraph

### ISSUE THREAD

**Issue by thmild** [mbojan/intergraph#25]
The following gives an error:

```
library(intergraph)
library(statnet)
gtrans(exNetwork)

```
```
error in if (is.edgelist.sna(z)) { : 
  argument is not interpretable as logical
In addition: Warning message:
In if (is.edgelist.sna(z)) { :
  the condition has length > 1 and only the first element will be used

```

The **warning** is also given with other network objects and is probably a problem in `network` / `sna`.

However, the **error** seems to occur only for network objects either converted from igraph using `asNetwork()` or the examples included with `intergraph`. Other basic network statistics like `degree()`, `gden()` etc. work! 

I use the version 2.0.3 of `intergraph` from github and the current CRAN version of all of `statnet`. Excerpt from `sessionInfo()`:

```
other attached packages:
 [1] statnet_2019.6        tsna_0.3.1            sna_2.5              
 [4] statnet.common_4.3.0  ergm.count_3.4.0      tergm_3.6.1          
 [7] networkDynamic_0.10.1 ergm_3.10.4           network_1.16.0       
[10] intergraph_2.0-3  

```

**Comment by thmild** [comment]
Ok, it is **NOT** a problem in `intergraph` but in `sna`. For some reason, `gtrans()` does not work when *any* edge attributes are present. The following still gives warnings but works:

```
library(intergraph)
library(statnet)
delete.edge.attribute(exNetwork, "label")
gtrans(exNetwork)
``` 
Sorry for the confusion!

**Comment by mbojan** [comment]
Thanks @thmild for reporting that anyway. I collaborate with Statnet crowd so I will pass your report (`sna` is not on GH).
