### ISSUE TITLE
`as.matrix.igraph()` does not seem to be called for igraph graphs

### ISSUE THREAD

**Issue by ntamas** [mbojan/intergraph#33]
I am preparing a new release of `igraph` and I noticed that the `intergraph` examples fail with `igraph`'s development version. In particular, calling `as.matrix(g, "adjacency")` fails because the method call is dispatched to `as.matrix.default()` and not `as.matrix.igraph()`.

This is what happens with the current official version of `igraph`:

```
> library(igraph)
> library(intergraph)
> g <- asIgraph(exNetwork)
> as.matrix(g, "adjacency")
IGRAPH 90c0896 D--- 15 11 --
+ attr: label (v/c), na (v/l), vertex.names (v/c), label (e/c), na
| (e/l)
+ edges from 90c0896:
 [1]  2-> 1  3-> 1  4-> 1  5-> 1  6-> 7  8-> 9 10->11 11->12 14->12 12->13
[11] 13->14
```

Note that the result is _not_ an adjacency matrix but the graph object itself. Calling `intergraph:::as.matrix.igraph()` directly works as expected. One can check that the `as.matrix` generic is dispatched to `as.matrix.default`:

```
> library(sloop)
> s3_dispatch(as.matrix(g, "adjacency"))
   as.matrix.igraph
=> as.matrix.default
```

Now, in the next version of igraph, the behaviour of `length(g)` will change; the earlier implementation was incorrect because the `[[` operator on `g` worked as if the user was indexing into the adjacency matrix of the graph, but `length(g)` did not return the number of vertices in the graph so `length(g)` was inconsistent with the `[[` operator even though `is.list(g)` returned `TRUE`. The change means that `as.matrix.default(g)` will no longer work for plain igraph graphs. `intergraph` should either be fixed so it exports `as.matrix.igraph`, _or_ I can move your implementation of `as.matrix.igraph` into `igraph` itself so you don't need to provide it on your own. Which one would be the preferred option?

**Comment by mbojan** [comment]
Thanks @ntamas for the heads-up! The quirky S3 dispatch...

I don't have a strong preference here. In the big picture perhaps it would make sense if `as.matrix.igraph()` in `igraph`. One thing to note is that I've changed some of the defaults (e.g. `sparse=FALSE`), but I'm fine if you decide to make it consistent with `as_adjacency_matrix()`.

**Comment by ntamas** [comment]
`as.matrix.igraph()` has been migrated to `igraph` in https://github.com/igraph/rigraph/commit/4e212dead29ed6db6482ff0851e2956829da8d92 . I also changed the defaults to be consistent with igraph in a80164f1 . Thanks for the original implementation!

**Comment by ntamas** [comment]
Also, moving `as.matrix.igraph()` to `igraph` itself has the nice side effect that the unit tests of `intergraph` no longer break with R-igraph 1.3.0.

**Comment by mbojan** [comment]
Following-up on this I'm removing `as.matrix.igraph` from the package.
